### ISSUE TITLE
Old accounts log in giving Null Pointer exception

### ISSUE THREAD

**Issue by FullBinaryAlchemist** [Rohan-RPJ/SecurityApplication#18]
Steps to reproduce:
1.Log in using users#skqaKma...

```
D/MainActivity: Inside setDeviceForSignIn method-Imei no.:866257031203002
D/Device Data Snapshot:: DataSnapshot { key = 866257031203002, value = {uid=null} }
D/MainActivity: Inside validateBeforeSignIn
    null
    Inside setUidFromFirebaseForSignIn
    dgdivyanshu@gmail,com
D/MainActivity: https://securityapplication-b990e.firebaseio.com/Email
D/Email Data Snapshot:: DataSnapshot { key = dgdivyanshu@gmail,com, value = * }
D/MainActivity: skqaKmaMzAgScM83gbzwwJOVZ203
    Inside isEmailRegistered
    skqaKmaMzAgScM83gbzwwJOVZ203
D/User Data Snapshot:: DataSnapshot { key = skqaKmaMzAgScM83gbzwwJOVZ203, value = {password=*, imei=null, location=Haan, dob=10/12/2019, mobile=*, sosContacts={c1=*, c2=*, c3=3636363366}, name=*, email=*, gender=female, googleAccountLinked=false} }
W/ClassMapper: No setter/field for password found on class com.example.securityapplication.model.User
D/MainActivity: No user not logged  in. Login the user
D/MainActivity: Signing IN user with email dgdivyanshu@gmail.com and password *
W/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@9a0620f
D/FirebaseAuth: Notifying id token listeners about user ( skqaKmaMzAgScM83gbzwwJOVZ203 ).
    Notifying auth state listeners about user ( skqaKmaMzAgScM83gbzwwJOVZ203 ).
D/MainActivity: onComplete: old user
D/MainActivity: https://securityapplication-b990e.firebaseio.com/Devices
I/Timeline: Timeline: Activity_launch_request time:636059082 intent:Intent { cmp=com.example.securityapplication/.navigation }
D/MainActivity: UI updated successfully
D/SOS Timer: Timer started
D/SOS Player: Inside onStartCOmmand : Stop =0
    detectSOSPattern initialised
W/MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
I/Toast: Show toast from OpPackageName:com.example.securityapplication, PackageName:com.example.securityapplication
D/SOS Timer: Time remaining:9
D/FirebaseHelper: FirebaseHelperInstance Exists
    Initializing Databse References... 
D/FirebaseHelper: Firebase Initialization complete
    Initializing Google SignIN Client
D/SQL: No. of rows in sql 0
D/SQL12: No. of rows in navigation1 0
D/SQL: No. of rows in sql 0
D/SQL: No. of rows in navigation 0
I/art: Do partial code cache collection, code=47KB, data=55KB
    After code cache collection, code=40KB, data=49KB
    Increasing code cache capacity to 256KB
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
I/Mainactivity destroyed: onDestroy!
W/ClassMapper: No setter/field for password found on class com.example.securityapplication.model.User
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.securityapplication, PID: 21611
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.example.securityapplication.model.User.isPaid(User.java:146)
        at com.example.securityapplication.navigation$2.onDataChange(navigation.java:153)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@17.0.0:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@17.0.0:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@17.0.0:55)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
I/Process: Sending signal. PID: 21611 SIG: 9
Process 21611 terminated.

```

**Comment by FullBinaryAlchemist** [comment]
Assign it to Sachin
